#! /bin/sh
### BEGIN INIT INFO
# Provides:          limacharlie
# Required-Start:    $local_fs $network $named
# Required-Stop:     $local_fs $network $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts limacharlie
# Description:       starts limacharlie using start-stop-daemon
### END INIT INFO
start() {
  cd /etc
  /bin/rphcp -d {{ install_key }} &
}
stop() {
  pkill -2 -f /bin/rphc
}
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status FOO
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0
